# Generated by Django 2.1.1 on 2019-09-14 20:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics & Communication Engineering')], default='CSE', max_length=15)),
                ('semester', models.IntegerField()),
                ('file', models.FileField(upload_to=books.models.get_file_path)),
            ],
        ),
    ]
