# Generated by Django 2.1.1 on 2019-09-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='semester',
            new_name='year',
        ),
    ]
